### ISSUE TITLE
NodeAliasPath is not a valid URL in version 13

### ISSUE THREAD

**Issue by bkehren** [drilic/kentico-mvcwidget-fullcalendar#10]
In the configuration when we initialize the pattern of the URL, the `NodeAliasPath` is not used for generating URLs in version 13.  To get the proper URL you need to use the `IPageUrlRetriever` interface per the [documentation](https://docs.xperience.io/developing-websites/retrieving-content/displaying-page-content#Displayingpagecontent-Retrievingpagedata)

If version 13 is not supported, I'd suggest modifying your documentation to show this component only works in version 12.

https://github.com/drilic/kentico-mvcwidget-fullcalendar/blob/455eacced10276bb210c3b10e2a6a8adca42dc86/EXLRT.Kentico.Mvc.Widgets.FullCalendar/Configuration/FullCalendarConfiguration.cs#L128

**Comment by drilic** [comment]
@bkehren This should be fixed based on your PR you submitted.
