### ISSUE TITLE
Adding new ConfigurationType

### ISSUE THREAD

**Issue by samytkhalil** [drilic/kentico-mvcwidget-fullcalendar#2]
Hello,

Thanks for providing this tool.

I tried it and added a new item in enum ConfigurationType as "Types"
` public enum FullCalendarConfigurationType
    {
        Pages,
        CustomTables,
        Classes,
        **Types**
    }`
 when adding the calendar into the page and select item of type "Types" the calendar appear but noting appear in the calendar dates

in applicationconfig.cs i added it as 

`.AddConfiguration("events", FullCalendarConfigurationType.Types, "MY.Events",
                                      "Events (Types)", "EventName", "StartDate", "EndDate")`

I tried to create a new object under custom tables and it works fine no problem

anything needed to make the Types appear in the calendar 

Thanks for  your help
Samy

**Comment by drilic** [comment]
Hey Samy,

Thank you for using this widget.

Regarding your comment above, I'm not really sure why you created new enum for Configuration Type. As you can see here, in [source code](https://github.com/drilic/kentico-mvcwidget-fullcalendar/blob/master/EXLRT.Kentico.Mvc.Widgets.FullCalendar/Controllers/FullCalendarApiController.cs), configuration types are used to determine which type of data you are handling for the specific widget and supported are:

- Pages (for cms.documents)
- CustomTables (for custom tables data)
- ModuleClasses (for classes used to store data in custom modules)

If you are working with _MY.Events_ which is the code name of the page type you should select _Pages_ from the enum and it will retrieve all events of that type.

If _Types_ is something new which is not covered by _Pages_, _CustomTables_ and _ModuleClasses_, usally something that comes from external API, you must handle that in FullCalendarApiController, specifically in GetData method:
```
public ActionResult GetCalendarData(string widgetType)
        {
            IEnumerable<FullCalendarEvent> data = new List<FullCalendarEvent>();
            FullCalendarWidgetConfiguration widgetConfiguration = FullCalendarConfiguration.GetWidgetConfiguration(widgetType);

            if (widgetConfiguration != null)
            {
                switch (widgetConfiguration.ConfigurationType)
                {
                    case FullCalendarConfigurationType.Pages:
                        data = this.FullCalendarEventsRepository.GetPageTypeEvents(widgetConfiguration);
                        break;

                    case FullCalendarConfigurationType.CustomTables:
                        data = this.FullCalendarEventsRepository.GetCustomTableEvents(widgetConfiguration);
                        break;

                    case FullCalendarConfigurationType.Classes:
                        data = this.FullCalendarEventsRepository.GetModuleClassEvents(widgetConfiguration);
                        break;
                }
            }

            return Json(JsonConvert.SerializeObject(data, new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore
            }), JsonRequestBehavior.AllowGet);
        }
```

If you have any other questions, please don't hesitate to contact me.

Best regards,
Dragoljub

**Comment by samytkhalil** [comment]
Thanks Dragoljub! I tried it with DancingGoat demo site and it is working fine with no code change, when I inspect my test project I found there is an error with url 
http://localhost:9095/en-US/fullcalendarapi/getcalendardata/Events

it throws an error, any idea where should I look at?

 `No parameterless constructor defined for this object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.MissingMethodException: No parameterless constructor defined for this object.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[MissingMethodException: No parameterless constructor defined for this object.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +142
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +107
   System.Activator.CreateInstance(Type type) +13
   System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +78

[InvalidOperationException: An error occurred when trying to create a controller of type 'EXLRT.Kentico.Mvc.Widgets.FullCalendar.Controllers.FullCalendarApiController'. Make sure that the controller has a parameterless public constructor.]
   System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +245
   System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) +103
   System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) +266
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +77
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +1128
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4075.0`

**Comment by drilic** [comment]
Samy,

That sounds to me like configuration issues with Dependency injection. Did you registered MVC calendar dependencies in DependencyResolverConfig.cs class, like [noted bellow](https://github.com/drilic/kentico-mvcwidget-fullcalendar#register-dependency-injection):

```
using EXLRT.Kentico.Mvc.Widgets.FullCalendar;
...
builder.RegisterFullCalendarDependencies();
```

Are you using same setup for DI as in Kentico Dancing Goat sample?

Best regards,
Dragoljub

**Comment by samytkhalil** [comment]
Hi Dragoljub,  

Thanks for the guidance I had have the calendar registered in the the DependencyResolverConfig.cs but in Global.asax.cs, the following registration was missing 
`            DependencyResolverConfig.Register();
`
After adjusting the global.asax.cs it works as expected.
